Axel dubar/feature/glossary
peerannot/peerannot.github.io pull request #3
Opened 2023-11-13 09:34 UTC by AxelDubar

Glossary page which is accessible at https://peerannot.github.io/glossary/ 
(or from the toolbar)

2023-11-13 14:41 UTC, josephsalmon commented
LGTM. @tanglef what about you?

2023-11-13 14:48 UTC, tanglef commented
> LGTM. @tanglef what about you?

@josephsalmon we had a discussion about adding the mathematical definition of labels (hard vs soft, class number vs vector in the simplex)  and then it's good for me too

2023-11-13 14:54 UTC, tanglef requested changes
Some notes on the definitions

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| identify       | Command that include the methods allowing to indentify difficult tasks or mislabeled labels |
difficult and/or mislabeled tasks and worker abilities

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| aggregate      | Command that include the methods allowing to aggregate label drom common noise model        |
label from common noise model

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| train          | Command that include the methods that train a model using aggregated data                   |
aggregated labels

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| aggregate-deep | Command that include the methods that train a model directly from the non aggregated data   |
from the raw collection of labels

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| $\pi^{(j)}$             | The confusion matrix of the worker $j$                                |
Mathematical definition: \pi^{(j)}_{k,\ell}=\mathbb{P}(y_i^{(j)​}=\ell∣y_i^\star​=k) \forall (\ell,k)\in [K]^2

2023-11-13 14:54 UTC, tanglef commented on _posts/2023-10-24-glossary.md
> +| K                       | The set of labels a task can take                                     |
[K] = \{1,...,K\} is the set, K alone is the number of possible labels

2023-11-17 13:01 UTC, tanglef commented
All good for me thanks !

2023-11-17 13:01 UTC, tanglef approved these changes

2023-11-17 13:01 UTC, merged